//go:build !ignore_autogenerated

/*
Copyright 2023 Enzo Nocera <enzo@nocera.eu>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by helpgen. DO NOT EDIT.

package markers

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Param) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "task",
		DetailedHelp: markers.DetailedHelp{
			Summary: "marks this struct as a parameter which can then be used as the target of an Unmarshalling operation",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"Name": {
				Summary: "is the name of your parameter",
				Details: "",
			},
			"Default": {
				Summary: "is the default value you wish to set your parameter at if unspecified",
				Details: "",
			},
			"Strict": {
				Summary: "",
				Details: "",
			},
		},
	}
}

func (Result) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "task",
		DetailedHelp: markers.DetailedHelp{
			Summary: "marks this struct as a result which can then be used as the target of a Marshalling operation",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"Name": {
				Summary: "is the name of the result",
				Details: "",
			},
		},
	}
}

func (Task) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "task",
		DetailedHelp: markers.DetailedHelp{
			Summary: "marks this executable package as a runnable task for Tekton",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"Name": {
				Summary: "is the name of your parameter",
				Details: "",
			},
			"Version": {
				Summary: "",
				Details: "",
			},
		},
	}
}
