//go:build !ignore_autogenerated

/*
Copyright 2023 Enzo Nocera <enzo@nocera.eu>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by helpgen. DO NOT EDIT.

package markers

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Param) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "task",
		DetailedHelp: markers.DetailedHelp{
			Summary: "tells Tektasker that this field can be used to receive the corresponding Task's param",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"Name": {
				Summary: "of your param",
				Details: "",
			},
			"Default": {
				Summary: "value for your param",
				Details: "",
			},
		},
	}
}
