/*
Copyright 2023 Enzo Nocera <enzo@nocera.eu>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package template

const DotEnvName = "dotenv"
const DotEnvTpl = `# This .env is generated by tektasker init

# Project

# Path to your internal non-reusable go packages
# Tektasker will add its internal package in it
PROJECT_INTERNAL_PKGS="internal/"

# Kustomization overlay to use when running "task apply"
PROJECT_TASK_OVERLAY="base"

# Name to use for the package containing tektasker internal helper code
TT_INTERNAL_PKG_NAME="tekton"

# Place where to write the Task manifest
TT_OUTPUT_MANIFEST=deployment/

# Which docker repository to push to
# Tips: if you are using KinD, "kind.local" seems to be a better option
# Please refer to official KO documentation
KO_DOCKER_REPO=ko.local

# Binaries Path
# Path to Kubectl
KUBECTL_PATH=kubectl

# Path to Tektasker
TT_PATH=tektasker

# Path to KO builder
KO_PATH=ko
`
